model:
  base_learning_rate: 4.5e-6
  target: taming.models.vcgan_cond_denoise.CVGAN_cond_sketch_1
  params:
    first_stage_config:
      target: taming.models.vcgan.VQModel
      params:
        ckpt_path: logs/2022-01-11T12-53-39_imagenet_vqgan/checkpoints/Epoch_30.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 1
            - 2
            - 2
            - 4
          num_res_blocks: 2
          attn_resolutions:
            - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 12
    train:
      target: taming.data.custom_cond_denoise.CustomTrain
      params:
        training_images_list_file: fish_train_UFO.txt
        cond_images_list_file: fish_train_UFO_sobel.txt
        target_images_list_file: fish_train_UFO_dn.txt
        size: 256
    validation:
      target: taming.data.custom_cond_denoise.CustomTest
      params:
        test_images_list_file: fish_test_UFO.txt
        cond_images_list_file: fish_test_UFO_sobel.txt
        test_target_images_list_file: fish_test_UFO_dn.txt
        size: 256

